const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94728899640"
const SESSION_ID = "PRABATH-MD~rXRnBCaK#e21s4Z9hTj4lYDAcmUBNOpMhoxTfWB-iHIKjb_66Z1Q"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
